GET http://127.0.0.1:10000/users/
Accept: application/json

###

POST http://127.0.0.1:10000/users/
Accept: application/json
Content-Type: application/json

{
  "username": "Admin",
  "password": "test",
  "role": "admin"
}

###

PATCH http://127.0.0.1:10000/users/5
Accept: application/json
Content-Type: application/json

{
  "password": "1478"
}

###

DELETE http://127.0.0.1:10000/users/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ilx1MDQyZVx1MDQxN1x1MDQxNVx1MDQyMCIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNjcxOTYzOTQzfQ.yEmzC8vNJRqW9PvzS6EhQ2XVI8WCO-kbq3lVamKz1ME

###