GET http://127.0.0.1:10000/users/
Accept: application/json

###

POST http://127.0.0.1:10000/users/
Accept: application/json
Content-Type: application/json

{
  "username": "User22",
  "password": "admin",
  "role": "user"
}

###

PATCH http://127.0.0.1:10000/users/6
Accept: application/json
Content-Type: application/json

{
  "password": "1478"
}

###

DELETE http://127.0.0.1:10000/users/5
#Content-Type: application/json
Authorization: "TOKEN"

###

DELETE http://127.0.0.1:10000/users/6
